services:
  cs-mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-backup:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - coffeeShop

  cs-spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - cs-mysql
    volumes:
      - .:/coffeeShop
    networks:
      - coffeeShop

networks:
  coffeeShop: