services:

  coffeeshop-mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coffeeshop
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-backup:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - coffeeShop

  coffeeshop-springboot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
       coffeeshop-mysql:
         condition: service_started
    volumes:
      - .:/coffeeShop
    networks:
      - coffeeShop

networks:
  coffeeShop: