services:
  coffeeShop:
    image: mysql:8.3.0
    container_name: coffeeShop
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-backup:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql